CREATE TABLE VIAJE (
COD VARCHAR(20),
ESTADO_CONVOY VARCHAR(20),
MIN_DEMORA VARCHAR(20),

CONSTRAINT PK_VIAJE PRIMARY KEY(COD)
);

CREATE TABLE BILLETE(
COD VARCHAR(20),
COD_VIAJE VARCHAR(20),
METODO_PAGO VARCHAR(20),
PRECIO INT(20),
ASIENTO VARCHAR(20),

CONSTRAINT PK_BILLETE PRIMARY KEY (COD,COD_VIAJE),
CONSTRAINT FK_BILLETE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE (COD)
);

CREATE TABLE PASAJERO (
DNI VARCHAR(20),
COD_BILLETE VARCHAR(20),
COD_VIAJE VARCHAR(20),
SEXO VARCHAR(20),
NOMBRE VARCHAR(20),
EDAD INT(20),
INDICARDOR_ASISTENCIA VARCHAR(2),
CONSTRAINT PK_PASAJERO PRIMARY KEY (DNI),
CONSTRAINT FK_PASAJERO_BILLETE FOREIGN KEY (COD_BILLETE,COD_VIAJE) REFERENCES BILLETE (COD,COD_VIAJE)


);

CREATE TABLE AVALA ( 
DNI_AVALA VARCHAR(20) NOT NULL,
DNI_AVALADO VARCHAR(20) NOT NULL,

CONSTRAINT PK_AVALA PRIMARY KEY (DNI_AVALA,DNI_AVALADO),
CONSTRAINT FK_AVALA_DNI_AVALA FOREIGN KEY (DNI_AVALA) REFERENCES PASAJERO (DNI),
CONSTRAINT FK_AVALA_DNI_AVALADOR FOREIGN KEY (DNI_AVALADO) REFERENCES PASAJERO (DNI)
);
CREATE TABLE COD_POSTALES(
CIUDAD VARCHAR(20),
COD_POSTAL VARCHAR(20),

CONSTRAINT PK_COD_POSTALES PRIMARY KEY (COD_POSTAL)
);
CREATE TABLE ESTACION( 
COD VARCHAR(20),
COD_POSTAL VARCHAR(20),
NUM_VIAS INT(20),

CONSTRAINT PK_ESTACION PRIMARY KEY (COD),
CONSTRAINT FK_ESTACION_POSTAL FOREIGN KEY (COD_POSTAL) REFERENCES COD_POSTALES (COD_POSTAL)
);

CREATE TABLE ESTACION_CATEGORIA(
COD_ESTACION VARCHAR(20),
CATEGORIA VARCHAR(20),

CONSTRAINT PK_ESTACION_CATEGORIA PRIMARY KEY (COD_ESTACION),
CONSTRAINT FK_ESTACION_CATEGORIA FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION (COD)
);
CREATE TABLE REALIZAN(
COD_ESTACION VARCHAR(20),
COD_VIAJE VARCHAR(20),

CONSTRAINT PK_REALIZAN PRIMARY KEY (COD_ESTACION,COD_VIAJE),
CONSTRAINT FK_REALIZAN_ESTACION FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION (COD),
CONSTRAINT FK_REALIZAN_VIAJE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE (COD)
);

CREATE TABLE PERSONAL ( 
DNI VARCHAR(20),
NSS VARCHAR(20),
NOMBRE VARCHAR(20),
APELLIDOS VARCHAR(20),
SALARIO_BASE INT(20),
ANTIGUEDAD INT(20),
COD_ESTACION VARCHAR(20),

CONSTRAINT PK_PERSONAL PRIMARY KEY (DNI),
CONSTRAINT FK_PERSONAL_ESTACION FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION (COD)
);

CREATE TABLE CONDUCTOR ( 
DNI VARCHAR(20),
LICENCIA VARCHAR(20),
EXPERIENCIA INT(20),
CONSTRAINT PK_CONDUCTOR  PRIMARY KEY (DNI),
CONSTRAINT FK_CONDUCTOR FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);
CREATE TABLE VIGILANTE ( 
DNI VARCHAR(20),
EMPRESA_EXTERNA VARCHAR(20),
NUMPLACA VARCHAR(20),
CONSTRAINT PK_VIGILANTE  PRIMARY KEY (DNI),
CONSTRAINT FK_VIGILANTE_PERSONAL FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);
CREATE TABLE ATENCION_AL_CLIENTE ( 
DNI VARCHAR(20),
PUESTO VARCHAR(20),

CONSTRAINT PK_ATENCION_AL_CLIENTE  PRIMARY KEY (DNI),
CONSTRAINT FK_ATENCION_AL_CLIENTE_PERSONAL FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);
CREATE TABLE ATENCION_AL_CLIENTE_IDIOMAS(
DNI VARCHAR(20),
IDIOMA_ADICIONAL VARCHAR(20),

CONSTRAINT PK_ATENCION_AL_CLIENTE_IDIOMAS  PRIMARY KEY (DNI),
CONSTRAINT FK_ATENCION_AL_CLIENTE_IDIOMAS FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)

);
CREATE TABLE RUTA(
COD VARCHAR(20),
DISTANCIA_TOTAL INT(20),
VELOCIDAD_MAXIMA INT(20),
COD_VIAJE VARCHAR(20),

CONSTRAINT PK_RUTA PRIMARY KEY (COD),
CONSTRAINT FK_RUTA_VIAJE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE (COD)
);

CREATE TABLE PARADA (
COD_RUTA VARCHAR(20),
COD VARCHAR(20),
VIA_LLEGADA INT(20),
TIEMPO_QUE_PERTENECE INT(20),

CONSTRAINT PK_PARADA PRIMARY KEY (COD_RUTA,COD),
CONSTRAINT FK_PARADA_RUTA FOREIGN KEY (COD_RUTA) REFERENCES RUTA (COD)
);

CREATE TABLE TREN (
MATRICULA VARCHAR(20),
MODELO VARCHAR(20),
FECHA_FAB DATE,

CONSTRAINT PK_TREN PRIMARY KEY (MATRICULA)
);

CREATE TABLE HACE(
MATRICULA VARCHAR(20),
COD_PARADA VARCHAR(20),
COD_RUTA VARCHAR(20),
DIA_SEMANA VARCHAR(20),
HORA_SALIDA INT(20),

CONSTRAINT PK_HACEN PRIMARY KEY (MATRICULA,COD_PARADA,COD_RUTA),
CONSTRAINT FK_HACEN_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA),
CONSTRAINT FK_HACEN_PARADA FOREIGN KEY (COD_RUTA,COD_PARADA) REFERENCES PARADA (COD_RUTA,COD)
);

CREATE TABLE REVISION (
COD_REVISION VARCHAR(20),
FECHA DATE,
COSTE INT(20),
TIPO_REPARACION VARCHAR(20),
MATRICULA VARCHAR(20),
CONSTRAINT PK_REVISION PRIMARY KEY (COD_REVISION),
CONSTRAINT FK_REVISION_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA)
);

CREATE TABLE VAGONES (
MATRICULA VARCHAR(20),
NUM_BASTIDOR INT(20),
CAPACIDAD INT(20),


CONSTRAINT PK_VAGONES PRIMARY KEY (MATRICULA,NUM_BASTIDOR),
CONSTRAINT PK_VAGONES_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA)
);
CREATE TABLE VAGONES_SERVICIOS(
MATRICULA VARCHAR(20),
NUM_BASTIDOR INT(20),
SERVICIOS VARCHAR(20),

CONSTRAINT PK_VAGONES_SERVICIOS PRIMARY KEY (MATRICULA,NUM_BASTIDOR),
CONSTRAINT PK_VAGONES_SERVICIOS_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA),
CONSTRAINT PK_VAGONES_SERVICIOS_VAGONES_SERVICIOS FOREIGN KEY (MATRICULA,NUM_BASTIDOR) REFERENCES VAGONES (MATRICULA,NUM_BASTIDOR)
);