CREATE TABLE VIAJE(
	COD VARCHAR2(10) NOT NULL,
	ESTADO_CONVOY VARCHAR2(25),
	MIN_DEMORA NUMBER(3),
	CONSTRAINT PK_VIAJE PRIMARY KEY (COD)
);

CREATE TABLE BILLETE(
	COD VARCHAR2(10) NOT NULL,
	COD_VIAJE VARCHAR2(10) NOT NULL,
	METODO_PAGO VARCHAR2(15),
	PRECIO NUMBER(3,2),
	ASIENTO VARCHAR(4),
	CONSTRAINT PK_BILLETE PRIMARY KEY (COD, COD_VIAJE),
	CONSTRAINT FK1_BILLETE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE(COD)
);

CREATE TABLE PASAJERO(
	DNI VARCHAR2(9) NOT NULL,
	SEXO VARCHAR2(1) NOT NULL,
	NOMBRE VARCHAR2(40) NOT NULL,
	EDAD NUMBER(3),
	INDICADOR_ASISTENCIA VARCHAR2(20),
	COD_BILLETE VARCHAR2(10),
	COD_VIAJE VARCHAR2(10),
	CONSTRAINT PK_PASAJERO PRIMARY KEY (DNI),
	CONSTRAINT FK_PASAJERO FOREIGN KEY (COD_BILLETE, COD_VIAJE) REFERENCES BILLETE(COD, COD_VIAJE)
);

CREATE TABLE AVALA(
	DNI_AVALA VARCHAR2(9) NOT NULL,
	DNI_AVALADO VARCHAR2(9) NOT NULL,
	CONSTRAINT PK_AVALA PRIMARY KEY (DNI_AVALA),
	CONSTRAINT FK1_AVALA FOREIGN KEY (DNI_AVALA) REFERENCES PASAJERO(DNI),
	CONSTRAINT FK2_AVALA FOREIGN KEY (DNI_AVALADO) REFERENCES PASAJERO(DNI)
);

CREATE TABLE ESTACION(
	COD VARCHAR2(10) NOT NULL,
	CIUDAD VARCHAR2(40),
	NOMBRE VARCHAR2(40),
	COD_POST NUMBER(5),
	NUM_VIAS VARCHAR2(3),
	CONSTRAINT PK_ESTACION PRIMARY KEY (COD)
);

CREATE TABLE ESTACION_CATEGORIAS(
	COD_ESTACION VARCHAR2(10) NOT NULL,
	CATEGORIA VARCHAR2(20),
	CONSTRAINT PK_ESTACION_CATEGORIAS PRIMARY KEY (COD_ESTACION),
	CONSTRAINT FK1_ESTACION_CATEGORIAS FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION(COD)
);

CREATE TABLE REALIZAN(
	COD_ESTACION VARCHAR2(10) NOT NULL,
	COD_VIAJE VARCHAR2(10) NOT NULL,
	CONSTRAINT PK_REALIZAN PRIMARY KEY (COD_ESTACION, COD_VIAJE),
	CONSTRAINT FK1_REALIZAN FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION(COD),
	CONSTRAINT FK2_REALIZAN FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE(COD)
);

CREATE TABLE PERSONAL(
	DNI VARCHAR2(9) NOT NULL,
	NSS VARCHAR2(12),
	NOMBRE VARCHAR2(15),
	APELLIDOS VARCHAR2(25),
	ANTIGUEDAD NUMBER(2),
	SALARIO_BASE NUMBER(4,2),
	COD_ESTACION VARCHAR2(10),
	CONSTRAINT PK_PERSONAL PRIMARY KEY (DNI),
	CONSTRAINT FK1_PERSONAL FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION(COD)
);

CREATE TABLE CONDUCTOR(
	DNI VARCHAR2(9) NOT NULL,
	LICENCIA VARCHAR2(20),
	EXPERIENCIA NUMBER(2),
	CONSTRAINT PK_CONDUCTOR PRIMARY KEY (DNI),
	CONSTRAINT FK1_CONDUCTOR FOREIGN KEY (DNI) REFERENCES PERSONAL(DNI)
);

CREATE TABLE VIGILANTE(
	DNI VARCHAR2(9) NOT NULL,
	EMPRESA_EXTERNA VARCHAR2(20),
	NUM_PLACA VARCHAR2(9),
	CONSTRAINT PK_VIGILANTE PRIMARY KEY (DNI),
	CONSTRAINT FK1_VIGILANTE FOREIGN KEY (DNI) REFERENCES PERSONAL(DNI)
);

CREATE TABLE ATENCION_AL_CLIENTE(
	DNI VARCHAR2(9) NOT NULL,
	PUESTO VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_ATENCION_AL_CLIENTE PRIMARY KEY (DNI),
	CONSTRAINT FK1_ATENCION_AL_CLIENTE FOREIGN KEY (DNI) REFERENCES PERSONAL(DNI)
);

CREATE TABLE ATENCION_AL_CLIENTE_IDIOMAS(
	DNI VARCHAR2(9) NOT NULL,
	IDIOMAS_ADICIONAL VARCHAR2(20),
	CONSTRAINT PK_ATENCION_AL_CLIENTE_IDIOMAS PRIMARY KEY (DNI),
	CONSTRAINT FK1_ATENCION_AL_CLIENTE_IDIOMAS FOREIGN KEY (DNI) REFERENCES ATENCION_AL_CLIENTE(DNI)
);

CREATE TABLE RUTA(
	COD VARCHAR2(10) NOT NULL,
	NOMBRE VARCHAR2(40),
	DISTANCIA_TOTAL VARCHAR2(7),
	VELOCIDAD_MAXIMA VARCHAR2(7),
	COD_VIAJE VARCHAR2(10) NOT NULL,
	CONSTRAINT PK_RUTA PRIMARY KEY (COD),
	CONSTRAINT FK1_RUTA FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE(COD)
);

CREATE TABLE PARADA(
	COD	VARCHAR2(10) NOT NULL,
	COD_RUTA VARCHAR2(10) NOT NULL,
	VIA_LLEGADA NUMBER(2),
	TIEMPO_QUE_PERMANECE NUMBER(3),
	CONSTRAINT PK_PARADA PRIMARY KEY (COD, COD_RUTA),
	CONSTRAINT FK1_PARADA FOREIGN KEY (COD_RUTA) REFERENCES RUTA(COD)
);

CREATE TABLE TREN(
	MATRICULA VARCHAR2(7) NOT NULL,
	MODELO VARCHAR2(20),
	FECHA_FAB DATE,
	CONSTRAINT PK_TREN PRIMARY KEY (MATRICULA)
);

CREATE TABLE HACEN(
	MATRICULA VARCHAR2(7) NOT NULL,
	COD_PARADA VARCHAR2(10) NOT NULL,
	COD_RUTA VARCHAR2(10) NOT NULL,
	DIA_SEMANA VARCHAR2(1),
	HORA_SALIDA NUMBER(2),
	CONSTRAINT PK_HACEN PRIMARY KEY (MATRICULA, COD_PARADA, COD_RUTA),
	CONSTRAINT FK1_HACEN FOREIGN KEY (MATRICULA) REFERENCES TREN(MATRICULA),
	CONSTRAINT FK2_HACEN FOREIGN KEY (COD_PARADA, COD_RUTA) REFERENCES PARADA(COD, COD_RUTA)
);

CREATE TABLE REVISION(
	COD_REVISION VARCHAR2(10) NOT NULL,
	FECHA DATE,
	COSTE NUMBER(4,2),
	TIPO_REPARACION VARCHAR2(20),
	MATRICULA VARCHAR2(7) NOT NULL,
	CONSTRAINT PK_REVISION PRIMARY KEY (COD_REVISION),
	CONSTRAINT FK1_REVISION FOREIGN KEY (MATRICULA) REFERENCES TREN(MATRICULA)
);

CREATE TABLE VAGONES(
	MATRICULA_TREN VARCHAR2(7) NOT NULL,
	NUMERO_BASTIDOR NUMBER(2) NOT NULL,
	CAPACIDAD NUMBER(3),
	CONSTRAINT PK_VAGONES PRIMARY KEY (MATRICULA_TREN, NUMERO_BASTIDOR),
	CONSTRAINT FK1_VAGONES FOREIGN KEY (MATRICULA_TREN) REFERENCES TREN(MATRICULA)
);

CREATE TABLE VAGONES_SERVICIOS(
	MATRICULA_TREN VARCHAR2(7) NOT NULL,
	NUMERO_BASTIDOR NUMBER(2) NOT NULL,
	SERVICIOS VARCHAR2(40),
	CONSTRAINT PK_VAGONES_SERVICIOS PRIMARY KEY (MATRICULA_TREN, NUMERO_BASTIDOR),
	CONSTRAINT FK1_VAGONES_SERVICIOS FOREIGN KEY (MATRICULA_TREN, NUMERO_BASTIDOR) REFERENCES VAGONES(MATRICULA_TREN, NUMERO_BASTIDOR)
);









