CREATE TABLE VIAJE (
COD VARCHAR2(20),
ESTADO_CONVOY VARCHAR2(20),
MIN_DEMORA VARCHAR2(20),

CONSTRAINT PK_VIAJE PRIMARY KEY(COD)
);

CREATE TABLE BILLETE(
COD VARCHAR2(20),
COD_VIAJE VARCHAR2(20),
METODO_PAGO VARCHAR2(20),
PRECIO NUMBER(20),
ASIENTO VARCHAR2(20),

CONSTRAINT PK_BILLETE PRIMARY KEY (COD,COD_VIAJE),
CONSTRAINT FK_BILLETE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE (COD)
);

CREATE TABLE PASAJERO (
DNI VARCHAR2(20),
COD_BILLETE VARCHAR2(20),
COD_VIAJE VARCHAR2(20),
SEXO VARCHAR2(20),
NOMBRE VARCHAR2(20),
EDAD NUMBER(20),
INDICARDOR_ASISTENCIA VARCHAR2(2),
CONSTRAINT PK_PASAJERO PRIMARY KEY (DNI),
CONSTRAINT FK_PASAJERO_BILLETE FOREIGN KEY (COD_BILLETE,COD_VIAJE) REFERENCES BILLETE (COD,COD_VIAJE)


);

CREATE TABLE AVALA ( 
DNI_AVALA VARCHAR2(20) NOT NULL,
DNI_AVALADO VARCHAR2(20) NOT NULL,

CONSTRAINT PK_AVALA PRIMARY KEY (DNI_AVALA,DNI_AVALADO),
CONSTRAINT FK_AVALA_DNI_AVALA FOREIGN KEY (DNI_AVALA) REFERENCES PASAJERO (DNI),
CONSTRAINT FK_AVALA_DNI_AVALADOR FOREIGN KEY (DNI_AVALADO) REFERENCES PASAJERO (DNI)
);
CREATE TABLE COD_POSTALES(
CIUDAD VARCHAR2(20),
COD_POSTAL VARCHAR2(20),

CONSTRAINT PK_COD_POSTALES PRIMARY KEY (COD_POSTAL)
);
CREATE TABLE ESTACION( 
COD VARCHAR2(20),
COD_POSTAL VARCHAR2(20),

NUM_VIAS NUMBER(20),

CONSTRAINT PK_ESTACION PRIMARY KEY (COD),
CONSTRAINT FK_ESTACION_COD_POSYAL FOREIGN KEY (COD_POSTAL) REFERENCES COD_POSTALES (COD_POSTAL)

);

CREATE TABLE ESTACION_CATEGORIA(
COD_ESTACION VARCHAR2(20),
CATEGORIA VARCHAR2(20),

CONSTRAINT PK_ESTACION_CATEGORIA PRIMARY KEY (COD_ESTACION),
CONSTRAINT FK_ESTACION_CATEGORIA FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION (COD)
);
CREATE TABLE REALIZAN(
COD_ESTACION VARCHAR2(20),
COD_VIAJE VARCHAR2(20),

CONSTRAINT PK_REALIZAN PRIMARY KEY (COD_ESTACION,COD_VIAJE),
CONSTRAINT FK_REALIZAN_ESTACION FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION (COD),
CONSTRAINT FK_REALIZAN_VIAJE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE (COD)
);

CREATE TABLE PERSONAL ( 
DNI VARCHAR2(20),
NSS VARCHAR2(20),
NOMBRE VARCHAR2(20),
APELLIDOS VARCHAR2(20),
SALARIO_BASE NUMBER(20),
ANTIGUEDAD NUMBER(20),
COD_ESTACION VARCHAR2(20),

CONSTRAINT PK_PERSONAL PRIMARY KEY (DNI),
CONSTRAINT FK_PERSONAL_ESTACION FOREIGN KEY (COD_ESTACION) REFERENCES ESTACION (COD)
);

CREATE TABLE CONDUCTOR ( 
DNI VARCHAR2(20),
LICENCIA VARCHAR2(20),
EXPERIENCIA NUMBER(20),
CONSTRAINT PK_CONDUCTOR  PRIMARY KEY (DNI),
CONSTRAINT FK_CONDUCTOR FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);
CREATE TABLE VIGILANTE ( 
DNI VARCHAR2(20),
EMPRESA_EXTERNA VARCHAR2(20),
NUMPLACA VARCHAR2(20),
CONSTRAINT PK_VIGILANTE  PRIMARY KEY (DNI),
CONSTRAINT FK_VIGILANTE_PERSONAL FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);
CREATE TABLE ATENCION_AL_CLIENTE ( 
DNI VARCHAR2(20),
PUESTO VARCHAR2(20),

CONSTRAINT PK_ATENCION_AL_CLIENTE  PRIMARY KEY (DNI),
CONSTRAINT FK_ATENCION_AL_CLIENTE_PERSONAL FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)
);
CREATE TABLE ATENCION_AL_CLIENTE_IDIOMAS(
DNI VARCHAR2(20),
IDIOMA_ADICIONAL VARCHAR2(20),

CONSTRAINT PK_ATENCION_AL_CLIENTE_IDIOMAS  PRIMARY KEY (DNI),
CONSTRAINT FK_ATENCION_AL_CLIENTE_IDIOMAS FOREIGN KEY (DNI) REFERENCES PERSONAL (DNI)

);
CREATE TABLE RUTA(
COD VARCHAR2(20),
DISTANCIA_TOTAL NUMBER(20),
VELOCIDAD_MAXIMA NUMBER(20),
COD_VIAJE VARCHAR2(20),

CONSTRAINT PK_RUTA PRIMARY KEY (COD),
CONSTRAINT FK_RUTA_VIAJE FOREIGN KEY (COD_VIAJE) REFERENCES VIAJE (COD)
);

CREATE TABLE PARADA (
COD_RUTA VARCHAR2(20),
COD VARCHAR2(20),
VIA_LLEGADA NUMBER(20),
TIEMPO_QUE_PERTENECE NUMBER(20),

CONSTRAINT PK_PARADA PRIMARY KEY (COD_RUTA,COD),
CONSTRAINT FK_PARADA_RUTA FOREIGN KEY (COD_RUTA) REFERENCES RUTA (COD)
);

CREATE TABLE TREN (
MATRICULA VARCHAR2(20),
MODELO VARCHAR2(20),
FECHA_FAB DATE,

CONSTRAINT PK_TREN PRIMARY KEY (MATRICULA)
);

CREATE TABLE HACE(
MATRICULA VARCHAR2(20),
COD_PARADA VARCHAR2(20),
COD_RUTA VARCHAR2(20),
DIA_SEMANA VARCHAR2(20),
HORA_SALIDA NUMBER(20),

CONSTRAINT PK_HACEN PRIMARY KEY (MATRICULA,COD_PARADA,COD_RUTA),
CONSTRAINT FK_HACEN_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA),
CONSTRAINT FK_HACEN_PARADA FOREIGN KEY (COD_RUTA,COD_PARADA) REFERENCES PARADA (COD_RUTA,COD)
);

CREATE TABLE REVISION (
COD_REVISION VARCHAR2(20),
FECHA DATE,
COSTE NUMBER(20),
TIPO_REPARACION VARCHAR2(20),
MATRICULA VARCHAR2(20),
CONSTRAINT PK_REVISION PRIMARY KEY (COD_REVISION),
CONSTRAINT FK_REVISION_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA)
);

CREATE TABLE VAGONES (
MATRICULA VARCHAR2(20),
NUM_BASTIDOR NUMBER(20),
CAPACIDAD NUMBER(20),


CONSTRAINT PK_VAGONES PRIMARY KEY (MATRICULA,NUM_BASTIDOR),
CONSTRAINT PK_VAGONES_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA)
);
CREATE TABLE VAGONES_SERVICIOS(
MATRICULA VARCHAR2(20),
NUM_BASTIDOR NUMBER(20),
SERVICIOS VARCHAR2(20),

CONSTRAINT PK_VAGONES_SERVICIOS PRIMARY KEY (MATRICULA,NUM_BASTIDOR),
CONSTRAINT PK_VAGONES_SERVICIOS_TREN FOREIGN KEY (MATRICULA) REFERENCES TREN (MATRICULA),
CONSTRAINT PK_VAGONES_SERVICIOS_VAGONES_SERVICIOS FOREIGN KEY (MATRICULA,NUM_BASTIDOR) REFERENCES VAGONES (MATRICULA,NUM_BASTIDOR)
);